### ISSUE TITLE
Remove spaces from formerly-indented blank lines #4638

### ISSUE THREAD

**Issue by joeack99** [tertty/neovim#1]
Neovim version: 0.1.3
Vim behaves differently?: no
Operating system/version: Linux Fedora 23
Terminal name/version: Gnome-terminal
$TERM: xterm-256color
Steps to reproduce using nvim -u NONE
nvim -u NONE

Type:

This is a test.
  This is indented.
Backspace over all contents of the second line, including the spaces.

All the text including the spaces are gone, but there still appear to be spaces rendered on the terminal. Typing new text will insert it at the beginning of the line, as it should with all spaces gone. But arrowing right/left does not reveal the presence of these spaces. They appear to be entirely gone from the file but are till rendered on the screen, likely aren't visible, and aren't used to indent when new text is added on the line.

Background
I am a blind screen reader user. I use the arrow keys rather than hjkl to navigate because screen readers don't know to present entire lines when hjkl are pressed, but they generally assume that the cursor moves in response to an arrow press so speak the updated change then. When I arrow to the second line in the above test data, after it is blank, my screen reader speaks "2 spaces", which is what it would speak before a line of text/whitespace that is indented. But, when typing text on that line, text is inserted at the beginning. As such, it is impossible to distinguish a line that actually has 2 spaces vs. one that had 2 and is now entirely blank. Vim does this too, is very annoying, and I hope Neovim might fix it.

To be very clear, these 2 spaces aren't in the file or editing buffer. They appear to be artifacts that aren't removed from the rendering, like istead of rendering the blank line as "\n\n" it's being rendered as "\n \n". It probably doesn't affect anyone other than screen reader users, so you may not notice it unless you dig into the rendering code.

**Comment by tertty** [comment]
Reached out to user that was having this issue because he did not provide enough details about replicating the bug, such as what text to speech program he used. Because of this, we were unable to replicate the bug despite deeply looking into the issue.
