### ISSUE TITLE
Error messages sometimes start with capital letter, sometimes not

### ISSUE THREAD

**Issue by ale28mar** [tertty/neovim#2]
For error messages, words are sometimes capitalized after colons:
("E682: Invalid ..." vs "E363: pattern ...")
- Operating system/version: Mac, Catalina
- Terminal name/version: Terminal

To reproduce this, one would have to do things so as to force the computer to print out an error. These are various, and different.

### Actual behaviour
("E682: Invalid ..." vs "E363: pattern ...")
### Expected behaviour
E682: Invalid ...
E363: Pattern ...
<img width="529" alt="Screen Shot 2019-11-05 at 1 51 36 PM" src="https://user-images.githubusercontent.com/49497544/68236598-781f2480-ffd3-11e9-8bdc-51b505a8ad74.png">

**Comment by ale28mar** [comment]
Error Number | Line on global.h | Corrected?
-- | -- | --
E906 | 942 |  
E906 | 944 |  
  | 946 |  
E73 | 1001 |  
  |   |

**Comment by tertty** [comment]
Pushed and merged with master, good job y'all :^)
